//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIngresProvider.Tests.TestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ansaettelse
    {
        public int medl_ident { get; set; }
        public int lbnr { get; set; }
        public int arbst_nr { get; set; }
        public System.DateTime fra_dato { get; set; }
        public System.DateTime til_dato { get; set; }
        public string form { get; set; }
        public decimal arbejds_time { get; set; }
        public string primaer_ansaettelse { get; set; }
        public System.DateTime reg_tid { get; set; }
        public string reg_init { get; set; }
        public int reg_vers_nr { get; set; }
    }
}
